// Windows-specific hardening. Metro's default cold-cache crawl opens one
// file handle per file it scans; combined with a large node_modules tree
// this can hit Windows' concurrent-handle limit (EMFILE) well before it
// would on macOS/Linux. Two mitigations: exclude directories Metro should
// never need to look inside, and cap worker concurrency so fewer files are
// open at once during that crawl.
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

// Extend, never replace, Expo/Metro's own default blockList -- it already
// excludes things that only exist after a native prebuild (android/, ios/,
// their build/.gradle artifact dirs, etc.). Overwriting it works fine
// locally (no native dirs are generated by a plain `expo export`) but
// breaks cloud builds, which bundle *after* prebuild has created them.
const defaultBlockList = Array.isArray(config.resolver.blockList)
  ? config.resolver.blockList
  : [config.resolver.blockList].filter(Boolean);

config.resolver.blockList = [
  ...defaultBlockList,
  /\/\.git\//,
  /\/dist\//,
  /\/docs\//,
  /\/supabase\//,
];

config.maxWorkers = 2;

module.exports = config;
