import type { QuranAyah, QuranContentPack } from '@/domain/types';

import generatedPack from './quran-pack-data.json';

// Al-Ikhlas: hand-reviewed pilot surah, on its own dedicated page (not tied
// to a real mushaf page number). Text and line boundaries are kept immutable
// (see quran-pack.test.ts checksum guard) and must not be regenerated from
// the bulk dataset used for the rest of Juz Amma below.
const alIkhlasSurah = {
  number: 112,
  nameArabic: 'الإخلاص',
  nameBn: 'আল-ইখলাস',
  ayahCount: 4,
};

const alIkhlasAyahs: QuranAyah[] = [
  {
    key: '112:1',
    surahNumber: 112,
    ayahNumber: 1,
    page: 1,
    lineStart: 1,
    lineEnd: 3,
    arabic: 'قُلْ هُوَ ٱللَّهُ أَحَدٌ',
    translationBn: 'বলুন, তিনি আল্লাহ, এক।',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/112001.mp3',
    lineDataVerified: true,
    lineDataSource: 'hand-reviewed-tanzil',
  },
  {
    key: '112:2',
    surahNumber: 112,
    ayahNumber: 2,
    page: 1,
    lineStart: 4,
    lineEnd: 6,
    arabic: 'ٱللَّهُ ٱلصَّمَدُ',
    translationBn: 'আল্লাহ অমুখাপেক্ষী।',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/112002.mp3',
    lineDataVerified: true,
    lineDataSource: 'hand-reviewed-tanzil',
  },
  {
    key: '112:3',
    surahNumber: 112,
    ayahNumber: 3,
    page: 1,
    lineStart: 7,
    lineEnd: 9,
    arabic: 'لَمْ يَلِدْ وَلَمْ يُولَدْ',
    translationBn: 'তিনি কাউকে জন্ম দেননি এবং তাঁকেও জন্ম দেওয়া হয়নি।',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/112003.mp3',
    lineDataVerified: true,
    lineDataSource: 'hand-reviewed-tanzil',
  },
  {
    key: '112:4',
    surahNumber: 112,
    ayahNumber: 4,
    page: 1,
    lineStart: 10,
    lineEnd: 13,
    arabic: 'وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌ',
    translationBn: 'এবং তাঁর সমতুল্য কেউ নেই।',
    audioUrl: 'https://everyayah.com/data/Alafasy_128kbps/112004.mp3',
    lineDataVerified: true,
    lineDataSource: 'hand-reviewed-tanzil',
  },
];

// Juz Amma pack: 36 surahs (78-114 excluding the Al-Ikhlas pilot above),
// generated by scripts/build-quran-pack.mjs from Tanzil-derived Arabic text
// and Bengali translation. Line/page boundaries come from Quran Foundation's
// Content API (mushaf id 7, IndoPak 16-line, 548 pages) — the published,
// named mushaf layout used by quran.com. Both the verse text and the layout
// trace to a recognised international authority, so every ayah ships with
// `lineDataVerified: true`; `lineDataSource` records which one produced the
// numbers.
export const quranDemoPack: QuranContentPack = {
  id: 'indopak-16-juz-amma',
  version: '2026.08-juzamma.3',
  layout: 'indopak-16',
  sourceName:
    'Tanzil Project (Al-Ikhlas, hand-reviewed) + risan/quran-json (Juz Amma Arabic/Bengali text) + Quran Foundation Content API (Juz Amma line/page layout, mushaf id 7)',
  sourceUrl: 'https://tanzil.net',
  checksumSha256: generatedPack.checksumSha256,
  surahs: [alIkhlasSurah, ...generatedPack.surahs].sort((a, b) => a.number - b.number),
  ayahs: [...alIkhlasAyahs, ...(generatedPack.ayahs as QuranAyah[])].sort(
    (a, b) => a.surahNumber - b.surahNumber || a.ayahNumber - b.ayahNumber,
  ),
};

export function getAyahs(keys: string[]) {
  const selected = new Set(keys);
  return quranDemoPack.ayahs.filter((ayah) => selected.has(ayah.key));
}
